export const SECRET_KEY = process.env.JWT_SECRET || "123456789";

export const SECTORS = [
    {
        name: "Tài chính",
        stocks: [
            "SHB",
            "VIX",
            "SSI",
            "MBB",
            "VPB",
            "VND",
            "VCI",
            "CTG",
            "EVS",
            "HCM",
            "VDS",
            "ORS",
            "STB",
            "ACB",
            "HDB",
        ],
    },
    {
        name: "Bất động sản",
        stocks: [
            "CEO",
            "NVL",
            "VRE",
            "LDG",
            "VHM",
            "DIG",
            "PDR",
            "DXG",
            "KDH",
            "SCR",
            "NLG",
            "VIC",
            "TCH",
            "DLG",
        ],
    },
    {
        name: "Công nghiệp",
        stocks: ["GEX", "HHV", "CII", "VSC", "VCG", "GMD", "PC1", "HAH"],
    },
    {
        name: "Thép và vật liệu cơ bản",
        stocks: [
            "HPG",
            "NKG",
            "HSG",
            "DPM",
            "DGC",
            "AAA",
            "GVR",
            "DCM",
            "BFC",
            "PLC",
        ],
    },
    {
        name: "Công nghệ Thông tin",
        stocks: ["FPT", "ELC", "CMG", "VTP", "ITD", "SAM"],
    },
    {
        name: "Bán lẻ & tiêu dùng",
        stocks: [
            "MWG",
            "PNJ",
            "VNM",
            "MSN",
            "SAB",
            "BHN",
            "HAG",
            "QNS",
            "KDC",
            "TLG",
        ],
    },
];
