import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/globals.css";
import { Providers } from "./providers";
import { AuthProvider } from "@/auth/AuthProvider";
import AuthGate from "@/auth/AuthGate";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";
import Loading from "@/share/components/Loading";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Fireant Stock",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthProvider>
                    <AuthGate>
                        <Providers>
                            {children}
                            <ToastContainer
                                position="top-right"
                                autoClose={3000}
                                pauseOnHover
                                newestOnTop
                                closeOnClick
                                theme="colored"
                            />
                        </Providers>
                    </AuthGate>
                </AuthProvider>
                {/* ⚡ SDK hiển thị TradingView */}
                <Script
                    src="https://s3.tradingview.com/tv.js"
                    strategy="beforeInteractive"
                />
            </body>
        </html>
    );
}
